### ISSUE TITLE
Sublime-Grasp doesn't work in Sublime Text 3.

### ISSUE THREAD

**Issue by bwinton** [joneshf/sublime-grasp#1]
(Copied from https://github.com/gkz/grasp/issues/1 )

To get it working in Sublime Text 3, I found I need to change `path.join` to `path.resolve` in grasp's index.js, and remove the `, shell=True` from the plugin's grasp.py. (And add a `setenv PATH …` line to my /etc/launchd.conf on OS X.)

**Comment by joneshf** [comment]
Sorry, I didn't see this until now. I'll check this out sometime this week.

**Comment by joneshf** [comment]
In fact, try this and see if it works. Might take about 15 mins to update though.

**Comment by bwinton** [comment]
I tried cloning your repo, but now it gives me this error:

Traceback (most recent call last):
  File "/Users/bwinton/Library/Application Support/Sublime Text 3/Packages/sublime-grasp/grasp.py", line 43, in run_grasp
    self.view.show(self.view.sel()[0])
  File "/Applications/Local/Sublime Text.app/Contents/MacOS/sublime.py", line 450, in **getitem**
    raise IndexError()

**Comment by gkz** [comment]
I've fixed an issue with Grasp where absolute paths did not work: gkz/grasp#6 - this may be relevant to your problem.

**Comment by gkz** [comment]
I released Grasp 0.2.0 today: http://graspjs.com/blog/2013/12/17/grasp-0.2.0-released/ which fixes the absolute path bug.

**Comment by joneshf** [comment]
@gkz Cool, thanks!

@bwinton Can you check if this fixed the issue?

**Comment by bwinton** [comment]
Well, I'm getting the same error, so I've done some tracing to try and figure out why.

It appears that when Grasp reports an error, it returns an empty array, which causes the `self.view.show(self.view.sel()[0])` to throw an IndexError.  So, I think you may want to change the `if result:` to `if result and not error:`.  (And/or maybe display the error somewhere?)

One other problem I've noticed is that the selection doesn't seem to show up, but I think that's [a Sublime Text bug](http://www.sublimetext.com/forum/viewtopic.php?f=6&t=13523&p=51945&hilit=view+updated#p51945).

Other than that, it seems fine, although it has shown me that Grasp doesn't handle some of the newer things I'm using, like "const".  ;)

Thanks,
Blake.

**Comment by gkz** [comment]
@bwinton Grasp uses [acorn](https://github.com/marijnh/acorn) to parse JavaScript, and it does not currently support ES6. It seems to be in its future however: marijnh/acorn#78. Once it updates with ES6 support Grasp will be updated to support it as well.
